# Generated by Django 4.2.6 on 2023-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_artwork_path_alter_artwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
