# Generated by Django 4.2.6 on 2023-11-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0005_alter_artwork_id_favoritedartworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedArtworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited', models.BooleanField(default=False)),
                ('artworkfK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.artwork')),
                ('userfK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='favoritedArtworks',
        ),
    ]
