# Generated by Django 4.2.6 on 2023-11-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_savedartworks_delete_favoritedartworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
