# Generated by Django 4.2.6 on 2023-11-29 04:40

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_artwork_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=collection.models.filepath)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='author',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='period',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='style',
        ),
        migrations.RemoveField(
            model_name='savedartworks',
            name='artworkfK',
        ),
        migrations.RemoveField(
            model_name='savedartworks',
            name='userfK',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='savedArtworks',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
