# Generated by Django 4.2.6 on 2023-11-30 06:04

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_item_remove_artwork_author_remove_artwork_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imageOriginal',
        ),
        migrations.AddField(
            model_name='item',
            name='imageProcessed1',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.filepath),
        ),
        migrations.AddField(
            model_name='item',
            name='imageProcessed2',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.filepath),
        ),
        migrations.AddField(
            model_name='item',
            name='imageProcessed3',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.filepath),
        ),
        migrations.AddField(
            model_name='item',
            name='imageProcessed4',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.filepath),
        ),
    ]
