# Generated by Django 4.2.6 on 2023-11-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_item_original_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_image_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
